### ISSUE TITLE
Logistic chest names wrong

### ISSUE THREAD

**Issue by BurnySc2** [kevinta893/factorio-recipes-json#4]
Hey, thank you for the repository!
It has been very useful to me.

However, I've noticed that the logistic chest names are wrong.

If you compare the requester chest for example:
https://github.com/kevinta893/factorio-recipes-json/blob/09a1e13a92796afd64c3db97f6c3f8b129d0fd89/recipes.json#L3421 with https://wiki.factorio.com/Requester_chest 
`Internal name: logistic-chest-requester`

I believe the other logistic chests are also wrong and should be:
```
logistic-chest-requester
logistic-chest-buffer
logistic-chest-passive-provider
logistic-chest-active-provider
logistic-chest-storage
```

**Comment by kevinta893** [comment]
Ah, I did not realize they had internal names. I just picked an 'id' that would be unique enough to search the list. This was done by taking the name and lowercasing the letters and replacing the spaces with dashes.

But yes I think I'll make the database more consistent with the wiki and the game by switching over to the internal name. I'll make those changes soon.

**Comment by BurnySc2** [comment]
Great to hear your decision!

I did find another wrongly named item, and that is https://github.com/kevinta893/factorio-recipes-json/blob/09a1e13a92796afd64c3db97f6c3f8b129d0fd89/recipes.json#L1039
which should be [effectivity-module](https://wiki.factorio.com/Efficiency_module).

**Comment by kevinta893** [comment]
Issue fixed in this [commit](https://github.com/kevinta893/factorio-recipes-json/commit/35e0fc1235210e6734e51af1b9a0555aa10b95cf)

Let me know if there are more internal name inconsistencies.


Edit: Update, fixed the id links that are referred to by the old internal names in some recipe ingredients. Thank goodness the test cases found this issue. Fixed commit here:
https://github.com/kevinta893/factorio-recipe-vis/commit/b42bafdd89663fcd99d910e20621edac9977f29d
